'use client'

import { useState } from 'react'
import { ArrowUpRight, BriefcaseBusiness, CheckCircle2, Handshake, Lightbulb, Send, Users, X, Zap } from 'lucide-react'

type Project = { id: string; name: string; challenge: string; university: string; district: string; domain: string; stage: string; support: string; funding: string }

const projects: Project[] = [
  { id: 'JH-2026-0018', name: 'Solar-powered irrigation pilot', challenge: 'Reliable irrigation for smallholder farmers', university: 'BIT Mesra', district: 'Khunti', domain: 'Agriculture', stage: 'Prototype', support: 'Funding, testing', funding: '₹18 lakh' },
  { id: 'JH-2026-0024', name: 'Digital health kiosk', challenge: 'Specialist healthcare access in rural clinics', university: 'Ranchi University', district: 'Gumla', domain: 'Healthcare', stage: 'Pilot-ready', support: 'Technology, deployment', funding: '₹12 lakh' },
  { id: 'JH-2026-0031', name: 'Accessible transit map', challenge: 'Public transport navigation for wheelchair users', university: 'XLRI Jamshedpur', district: 'East Singhbhum', domain: 'Accessibility', stage: 'Research', support: 'Mentorship, prototyping', funding: '₹6 lakh' },
]
const recommendations = [['Biogas for community kitchens', 'Energy', 'Central University of Jharkhand', '94%', 'Circular economy', 'Equipment'], ['Cold-chain micro hubs', 'Agriculture', 'Birsa Agricultural University', '88%', 'Operations and logistics', 'Funding'], ['Tribal language learning app', 'Education', 'Ranchi University', '82%', 'Product design', 'Technology']]
const collaborations = [['Solar irrigation pilot', 'BIT Mesra', 'Technology Partner', 'Sensors + testing', 'Prototype', '72%', 'Active'], ['School water audit', 'NIT Jamshedpur', 'CSR Partner', '₹8 lakh grant', 'Pilot', '48%', 'Active'], ['Digital health kiosk', 'Ranchi University', 'Implementation Partner', 'Clinical mentorship', 'Pilot-ready', '86%', 'On track']]

function Section({ eyebrow, title, children }: { eyebrow: string; title: string; children: React.ReactNode }) { return <section className="rounded-2xl border border-slate-200 bg-white p-6"><p className="text-[11px] font-bold uppercase tracking-wider text-orange-700">{eyebrow}</p><h2 className="mt-1 mb-5 text-lg font-bold text-slate-950">{title}</h2>{children}</section> }
function Stat({ label, value, icon: Icon }: { label: string; value: string; icon: typeof Users }) { return <div className="rounded-2xl border border-slate-200 bg-white p-5"><div className="flex items-start justify-between gap-2"><div><p className="text-sm text-slate-500">{label}</p><p className="mt-2 text-3xl font-bold text-slate-950">{value}</p></div><span className="grid size-10 place-items-center rounded-xl bg-emerald-50 text-emerald-700"><Icon className="size-5" /></span></div></div> }

export default function IndustryDashboard() {
  const [modal, setModal] = useState<Project | null>(null)
  const [sent, setSent] = useState(false)
  const [toast, setToast] = useState('')
  const action = (label: string) => { setToast(`${label} selected`); window.setTimeout(() => setToast(''), 1800) }
  return <div className="relative min-h-full bg-slate-50 p-5 sm:p-8"><div className="mx-auto max-w-[1450px]">
    {toast && <div className="fixed bottom-5 right-5 z-40 rounded-xl bg-emerald-900 px-4 py-3 text-sm font-semibold text-white shadow-lg" role="status">{toast}</div>}
    <div className="flex flex-col justify-between gap-4 md:flex-row md:items-end"><div><p className="text-xs font-medium text-slate-400">Partner workspace</p><h2 className="mt-1 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Industry &amp; Innovation Partners</h2><p className="mt-2 max-w-2xl text-sm leading-6 text-slate-500">Find promising projects and help turn research into real-world impact.</p></div><button onClick={() => action('Discover Projects')} className="flex w-fit items-center gap-2 rounded-lg bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white">Discover Projects <ArrowUpRight className="size-4" /></button></div>
    <div className="mt-7 grid gap-4 sm:grid-cols-2 xl:grid-cols-6"><Stat label="Projects Seeking Support" value="24" icon={Lightbulb} /><Stat label="Active Collaborations" value="08" icon={Handshake} /><Stat label="Projects Supported" value="17" icon={CheckCircle2} /><Stat label="Mentorships" value="32" icon={Users} /><Stat label="Funding Committed" value="₹2.4 Cr" icon={BriefcaseBusiness} /><Stat label="Solutions Deployed" value="09" icon={Zap} /></div>
    <div className="mt-8 grid gap-6 xl:grid-cols-[1.25fr_.75fr]"><Section eyebrow="Make an impact" title="Projects looking for support"><div className="grid gap-4">{projects.map(p => <article key={p.id} className="rounded-xl border border-slate-200 p-4"><div className="flex flex-col justify-between gap-3 sm:flex-row"><div><div className="flex flex-wrap items-center gap-2"><span className="text-[11px] font-bold text-emerald-700">{p.id}</span><span className="rounded-full bg-orange-50 px-2 py-1 text-[11px] font-bold text-orange-700">{p.stage}</span></div><h3 className="mt-2 font-bold text-slate-950">{p.name}</h3><p className="mt-1 text-xs text-slate-500">{p.university} · {p.district} · {p.domain}</p></div><span className="text-sm font-bold text-slate-900">{p.funding}</span></div><p className="mt-3 text-xs text-slate-500">Original challenge: <span className="text-slate-700">{p.challenge}</span></p><p className="mt-2 text-xs font-semibold text-slate-500">Support required: <span className="text-slate-800">{p.support}</span></p><div className="mt-4 flex gap-2"><button onClick={() => window.location.href = `/projects/${p.id}`} className="rounded-lg border border-slate-200 px-3 py-2 text-xs font-bold text-slate-700">View Project</button><button onClick={() => { setSent(false); setModal(p) }} className="rounded-lg bg-emerald-800 px-3 py-2 text-xs font-bold text-white">Offer Support</button></div></article>)}</div></Section><Section eyebrow="Smart discovery" title="Recommended projects"><p className="-mt-3 mb-4 text-xs text-slate-400">AI match scores are demo/mock data.</p><div className="space-y-3">{recommendations.map(([name, domain, uni, score, expertise, need]) => <div key={name} className="rounded-xl bg-slate-50 p-4"><div className="flex items-start justify-between gap-3"><div><h3 className="text-sm font-bold text-slate-950">{name}</h3><p className="mt-1 text-xs text-slate-500">{domain} · {uni}</p></div><span className="text-sm font-bold text-emerald-700">{score} match</span></div><p className="mt-3 text-xs text-slate-600">Required expertise: <b>{expertise}</b> · Support needed: <b>{need}</b></p></div>)}</div></Section></div>
    <div className="mt-6 grid gap-6 xl:grid-cols-[1.35fr_.65fr]"><Section eyebrow="Working together" title="Active collaborations"><div className="overflow-x-auto"><table className="w-full min-w-[900px] text-left text-xs"><thead className="border-b border-slate-100 text-slate-400"><tr>{['Project','University','Partner role','Support provided','Stage','Progress','Status','Action'].map(x => <th key={x} className="pb-3 pr-4 font-bold">{x}</th>)}</tr></thead><tbody>{collaborations.map(r => <tr key={r[0]} className="border-b border-slate-100 last:border-0">{r.map((cell, i) => <td key={cell} className={`py-4 pr-4 ${i === 0 ? 'font-bold text-slate-900' : i > 4 ? 'font-bold text-emerald-700' : 'text-slate-600'}`}>{cell}</td>)}<td className="py-4"><button onClick={() => action('View collaboration')} className="font-bold text-emerald-800">Open</button></td></tr>)}</tbody></table></div></Section><Section eyebrow="Join the network" title="Mentorship opportunities"><div className="space-y-4">{[['Water quality sensors','BIT Mesra','IoT and field testing','4 hrs / month'],['Rural health UX','Ranchi University','Service design','2 hrs / week'],['Agri supply chains','BAU Ranchi','Market access','6 hrs / month']].map(r => <div key={r[0]}><h3 className="text-sm font-bold text-slate-950">{r[0]}</h3><p className="mt-1 text-xs text-slate-500">{r[1]} · {r[2]}</p><p className="mt-1 text-xs font-semibold text-orange-700">{r[3]}</p><button onClick={() => action('Mentor request')} className="mt-2 text-xs font-bold text-emerald-800">Become a Mentor <ArrowUpRight className="inline size-3" /></button></div>)}</div></Section></div>
    <div className="mt-6 grid gap-6 md:grid-cols-3"><Section eyebrow="Resources" title="Funding & support"><div className="grid grid-cols-2 gap-4 text-sm">{[['Funding committed','₹2.4 Cr'],['Funding utilized','₹1.6 Cr'],['Projects funded','17'],['Equipment provided','28'],['Mentorship hours','486']].map(([a,b]) => <div key={a}><p className="text-slate-500">{a}</p><b className="text-xl text-slate-950">{b}</b></div>)}</div></Section><Section eyebrow="Impact" title="Innovation outcomes"><div className="grid grid-cols-2 gap-4 text-sm">{[['Prototypes supported','36'],['Pilots completed','14'],['Solutions deployed','09'],['Startups created','07'],['Patents / IP','11'],['Communities reached','42']].map(([a,b]) => <div key={a}><b className="text-xl text-slate-950">{b}</b><p className="text-slate-500">{a}</p></div>)}</div></Section><Section eyebrow="Live feed" title="Recent activity"><div className="space-y-3 text-xs">{['Industry joined Solar irrigation pilot','Funding approved for School water audit','Mentor assigned to Digital health kiosk','Prototype testing started','Pilot completed in Gumla'].map((x, i) => <div key={x} className="flex gap-2"><span className="mt-1 size-2 shrink-0 rounded-full bg-orange-500" /><div><b className="text-slate-800">{x}</b><p className="mt-1 text-slate-400">{i + 1} day{i ? 's' : ''} ago</p></div></div>)}</div></Section></div>
    <Section eyebrow="Partner toolkit" title="Quick actions"><div className="flex flex-wrap gap-3">{['Discover Projects','Offer Support','Become a Mentor','View Collaborations','View Impact'].map(label => <button key={label} onClick={() => label === 'Offer Support' ? setModal(projects[0]) : action(label)} className="rounded-lg border border-slate-200 px-4 py-2.5 text-sm font-bold text-slate-700 hover:border-emerald-300 hover:text-emerald-800">{label}</button>)}</div></Section>
  </div>{modal && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="offer-title" className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-wider text-orange-700">Partnership offer</p><h2 id="offer-title" className="mt-1 text-xl font-bold text-slate-950">Support a promising project</h2></div><button onClick={() => setModal(null)} aria-label="Close dialog"><X className="size-5 text-slate-500" /></button></div>{sent ? <div className="py-10 text-center"><CheckCircle2 className="mx-auto size-12 text-emerald-700" /><h3 className="mt-4 text-lg font-bold">Offer sent for review</h3><p className="mt-2 text-sm text-slate-500">The project team will be notified of your partnership interest.</p></div> : <form onSubmit={e => { e.preventDefault(); setSent(true) }} className="mt-6 space-y-4"><label className="block text-sm font-semibold text-slate-700">Project<input value={modal.name} readOnly className="mt-1 w-full rounded-lg border border-slate-200 bg-slate-50 px-3 py-2.5 text-sm" /></label><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-700">Support type<select className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm"><option>Funding</option><option>Mentorship</option><option>Technology</option><option>Equipment</option><option>Testing</option></select></label><label className="block text-sm font-semibold text-slate-700">Organization<input required className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label></div><div className="grid gap-4 sm:grid-cols-2"><label className="block text-sm font-semibold text-slate-700">Contact person<input required className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="block text-sm font-semibold text-slate-700">Funding amount<input type="number" min="0" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label></div><label className="block text-sm font-semibold text-slate-700">Support details<textarea required rows={3} className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><label className="block text-sm font-semibold text-slate-700">Expected timeline<input required placeholder="e.g. 3 months" className="mt-1 w-full rounded-lg border border-slate-200 px-3 py-2.5 text-sm" /></label><button className="flex w-full items-center justify-center gap-2 rounded-lg bg-emerald-800 px-4 py-3 text-sm font-bold text-white" type="submit"><Send className="size-4" />Send Partnership Offer</button></form>}</div></div>}
  </div>
}

export { projects }
