'use client'

import { useState } from 'react'
import { ArrowLeft, ArrowUpRight, CalendarDays, Check, CheckCircle2, ChevronRight, Circle, FileText, Flag, MessageSquare, MoreHorizontal, Paperclip, Plus, Send, ShieldCheck, Users, Wrench, X } from 'lucide-react'

type ProjectManagementProps = { projectId: string }

const lifecycle = ['Challenge assigned', 'Challenge accepted', 'Team formed', 'Proposal approved', 'Prototype developed', 'Field testing', 'Deployment']
const milestones = [
  ['Research & discovery', '30 Jun 2026', 'Completed', '100%'],
  ['Prototype build', '18 Jul 2026', 'In progress', '68%'],
  ['Field testing in Khunti', '30 Sep 2026', 'Upcoming', '0%'],
  ['Impact evaluation', '20 Oct 2026', 'Upcoming', '0%'],
]
const activity = [
  ['Prototype testing started', 'Dr. Meera Singh uploaded a field testing plan.', 'Today, 10:42 AM'],
  ['Industry partner joined', 'Tata Trusts offered sensors and testing support.', 'Yesterday, 4:18 PM'],
  ['Milestone completed', 'Research & discovery was marked complete.', '20 Jun 2026'],
]

function Card({ eyebrow, title, children, action }: { eyebrow: string; title: string; children: React.ReactNode; action?: string }) {
  return <section className="rounded-2xl border border-slate-200 bg-white p-5 sm:p-6"><div className="mb-5 flex items-end justify-between gap-4"><div><p className="text-[11px] font-bold uppercase tracking-wider text-orange-700">{eyebrow}</p><h2 className="mt-1 text-lg font-bold text-slate-950">{title}</h2></div>{action && <button className="hidden items-center gap-1 text-xs font-bold text-emerald-800 sm:flex">{action}<ArrowUpRight className="size-3.5" /></button>}</div>{children}</section>
}
function Status({ children, tone = 'green' }: { children: React.ReactNode; tone?: 'green' | 'orange' | 'slate' }) { return <span className={`rounded-full px-2 py-1 text-[11px] font-bold ${tone === 'green' ? 'bg-emerald-50 text-emerald-700' : tone === 'orange' ? 'bg-orange-50 text-orange-700' : 'bg-slate-100 text-slate-600'}`}>{children}</span> }

export default function ProjectManagement({ projectId }: ProjectManagementProps) {
  const [toast, setToast] = useState('')
  const [message, setMessage] = useState('')
  const [showComposer, setShowComposer] = useState(false)
  const notify = (text: string) => { setToast(text); window.setTimeout(() => setToast(''), 1800) }
  return <main className="relative min-h-full bg-slate-50 p-5 sm:p-8">
    {toast && <div className="fixed bottom-5 right-5 z-50 rounded-xl bg-emerald-900 px-4 py-3 text-sm font-semibold text-white shadow-lg" role="status">{toast}</div>}
    <div className="mx-auto max-w-[1450px]">
      <button onClick={() => window.history.back()} className="mb-5 flex items-center gap-2 text-sm font-bold text-emerald-800"><ArrowLeft className="size-4" />Back to workspace</button>
      <div className="flex flex-col justify-between gap-5 md:flex-row md:items-end"><div><div className="flex flex-wrap items-center gap-2"><span className="text-xs font-bold text-emerald-700">{projectId}</span><Status tone="orange">Prototype</Status><Status>On track</Status></div><h1 className="mt-2 text-2xl font-bold tracking-tight text-slate-950 sm:text-3xl">Solar-powered irrigation pilot</h1><p className="mt-2 max-w-3xl text-sm leading-6 text-slate-500">Reliable irrigation for smallholder farmers in Khunti through affordable solar-powered water systems.</p><div className="mt-4 flex flex-wrap gap-x-5 gap-y-2 text-xs font-semibold text-slate-500"><span>Khunti district</span><span>Agriculture</span><span>BIT Mesra</span><span>Deadline: 30 Sep 2026</span></div></div><div className="flex gap-2"><button onClick={() => notify('Project report exported')} className="rounded-lg border border-slate-200 bg-white px-4 py-2.5 text-sm font-bold text-slate-700">Export report</button><button onClick={() => setShowComposer(true)} className="flex items-center gap-2 rounded-lg bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white"><MessageSquare className="size-4" />Message team</button></div></div>

      <Card eyebrow="Project lifecycle" title="Delivery progress"><div className="grid gap-3 md:grid-cols-7">{lifecycle.map((stage, i) => <div key={stage} className="relative flex items-center gap-3 md:block md:text-center"><div className={`mx-0 grid size-9 shrink-0 place-items-center rounded-full md:mx-auto ${i < 4 ? 'bg-emerald-800 text-white' : i === 4 ? 'bg-orange-500 text-white' : 'border-2 border-slate-200 bg-white text-slate-300'}`}>{i < 4 ? <Check className="size-4" /> : i === 4 ? <Wrench className="size-4" /> : <Circle className="size-3" />}</div><p className={`text-xs md:mt-2 ${i === 4 ? 'font-bold text-orange-700' : i < 4 ? 'font-semibold text-slate-700' : 'text-slate-400'}`}>{stage}</p>{i < lifecycle.length - 1 && <ChevronRight className="absolute right-1 hidden size-4 text-slate-300 md:block" />}</div>)}</div><div className="mt-6 h-2 rounded-full bg-slate-100"><div className="h-full w-[68%] rounded-full bg-emerald-700" /></div><div className="mt-2 flex justify-between text-xs font-semibold text-slate-400"><span>68% complete</span><span>Current stage: Prototype developed</span></div></Card>

      <div className="mt-6 grid gap-6 xl:grid-cols-[1.15fr_.85fr]"><Card eyebrow="Delivery plan" title="Milestones & deliverables" action="View project plan"><div className="overflow-x-auto"><table className="w-full min-w-[620px] text-left text-xs"><thead className="border-b border-slate-100 text-[10px] uppercase tracking-wider text-slate-400"><tr><th className="pb-3">Milestone</th><th className="pb-3">Due date</th><th className="pb-3">Status</th><th className="pb-3">Progress</th><th className="pb-3">Action</th></tr></thead><tbody>{milestones.map(([name, date, status, progress]) => <tr key={name} className="border-b border-slate-50 last:border-0"><td className="py-4 font-bold text-slate-800">{name}</td><td className="py-4 whitespace-nowrap text-slate-500">{date}</td><td className="py-4"><Status tone={status === 'In progress' ? 'orange' : status === 'Upcoming' ? 'slate' : 'green'}>{status}</Status></td><td className="py-4"><div className="flex items-center gap-2"><div className="h-2 w-16 rounded-full bg-slate-100"><div className="h-full rounded-full bg-emerald-700" style={{ width: progress }} /></div><span className="font-bold text-slate-600">{progress}</span></div></td><td className="py-4"><button onClick={() => notify(`${name} selected`)} className="font-bold text-emerald-800">Open</button></td></tr>)}</tbody></table></div></Card><Card eyebrow="People" title="Project team"><div className="space-y-3">{[['Dr. Meera Singh', 'Faculty mentor', 'Agricultural Engineering'], ['Arjun Kumar', 'Student lead', 'Computer Science'], ['Priya Das', 'Field research', 'Civil Engineering'], ['Tata Trusts', 'Industry partner', 'Technology and testing']].map(([name, role, detail]) => <div key={name} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className="grid size-9 place-items-center rounded-full bg-orange-50 text-orange-700"><Users className="size-4" /></span><div className="min-w-0 flex-1"><p className="text-sm font-bold text-slate-800">{name}</p><p className="text-xs text-slate-500">{role} · {detail}</p></div><button onClick={() => notify(`Opening ${name}`)} aria-label={`Open ${name}`}><MoreHorizontal className="size-4 text-slate-400" /></button></div>)}</div><button onClick={() => notify('Invite flow selected')} className="mt-4 flex w-full items-center justify-center gap-2 rounded-lg border border-emerald-200 px-4 py-2.5 text-sm font-bold text-emerald-800"><Plus className="size-4" />Invite collaborator</button></Card></div>

      <div className="mt-6 grid gap-6 xl:grid-cols-[.9fr_1.1fr]"><Card eyebrow="Solution design" title="Proposal & prototype"><div className="rounded-xl bg-slate-50 p-4"><div className="flex items-center gap-3"><span className="grid size-9 place-items-center rounded-lg bg-white text-emerald-800"><FileText className="size-4" /></span><div><p className="text-sm font-bold text-slate-800">Solar irrigation system v2</p><p className="text-xs text-slate-500">Approved 12 Jun 2026 · 8 pages</p></div></div><p className="mt-4 text-sm leading-6 text-slate-600">A modular solar pump and soil-moisture sensor kit designed for community-managed farms.</p><button onClick={() => notify('Proposal opened')} className="mt-3 text-xs font-bold text-emerald-800">View proposal <ArrowUpRight className="inline size-3" /></button></div><div className="mt-4 grid grid-cols-2 gap-3"><div className="rounded-xl border border-slate-100 p-3"><p className="text-xs text-slate-500">Prototype version</p><p className="mt-1 text-lg font-bold text-slate-950">v2.1</p></div><div className="rounded-xl border border-slate-100 p-3"><p className="text-xs text-slate-500">Testing status</p><p className="mt-1 text-lg font-bold text-orange-700">In lab</p></div></div></Card><Card eyebrow="Readiness" title="Deployment checklist"><div className="space-y-3">{[['Hardware safety review', true], ['Field partner confirmed', true], ['User training materials', true], ['District permissions', false], ['Impact baseline collected', false]].map(([label, done]) => <div key={label as string} className="flex items-center gap-3 rounded-xl border border-slate-100 p-3"><span className={`grid size-7 place-items-center rounded-full ${done ? 'bg-emerald-100 text-emerald-700' : 'bg-slate-100 text-slate-400'}`}>{done ? <CheckCircle2 className="size-4" /> : <Flag className="size-4" />}</span><span className={`flex-1 text-sm font-semibold ${done ? 'text-slate-700' : 'text-slate-500'}`}>{label as string}</span><span className="text-xs font-bold text-slate-400">{done ? 'Done' : 'Pending'}</span></div>)}</div></Card></div>

      <div className="mt-6 grid gap-6 xl:grid-cols-[1fr_.8fr]"><Card eyebrow="Project communication" title="Recent updates" action="View all activity"><div className="space-y-5">{activity.map(([title, detail, time]) => <div key={title} className="flex gap-3"><span className="mt-1 size-2 shrink-0 rounded-full bg-orange-500" /><div><p className="text-sm font-bold text-slate-800">{title}</p><p className="mt-1 text-xs leading-5 text-slate-500">{detail}</p><p className="mt-1 text-[11px] text-slate-400">{time}</p></div></div>)}</div></Card><Card eyebrow="Outcomes" title="Impact & budget"><div className="grid grid-cols-2 gap-4">{[['Farmers reached','120'],['Water saved','32%'],['Budget','₹18 lakh'],['Utilized','₹10.4 lakh']].map(([label, value]) => <div key={label}><p className="text-xs text-slate-500">{label}</p><p className="mt-1 text-xl font-bold text-slate-950">{value}</p></div>)}</div><div className="mt-5 border-t border-slate-100 pt-4"><div className="flex justify-between text-xs font-semibold text-slate-500"><span>Budget utilization</span><span>58%</span></div><div className="mt-2 h-2 rounded-full bg-slate-100"><div className="h-full w-[58%] rounded-full bg-orange-500" /></div></div></Card></div>
    </div>
    {showComposer && <div className="fixed inset-0 z-50 grid place-items-center bg-slate-950/40 p-4"><div role="dialog" aria-modal="true" aria-labelledby="message-title" className="w-full max-w-lg rounded-2xl bg-white p-6 shadow-2xl"><div className="flex items-start justify-between"><div><p className="text-[11px] font-bold uppercase tracking-wider text-orange-700">Team communication</p><h2 id="message-title" className="mt-1 text-xl font-bold text-slate-950">Message project team</h2></div><button onClick={() => setShowComposer(false)} aria-label="Close dialog"><X className="size-5 text-slate-500" /></button></div><textarea value={message} onChange={e => setMessage(e.target.value)} placeholder="Write an update or question..." className="mt-6 min-h-32 w-full rounded-xl border border-slate-200 p-3 text-sm outline-none focus:border-emerald-500" /><div className="mt-4 flex justify-between"><button onClick={() => notify('Attachment flow selected')} className="flex items-center gap-2 text-xs font-bold text-slate-500"><Paperclip className="size-4" />Attach file</button><button onClick={() => { setShowComposer(false); setMessage(''); notify('Message sent to the team') }} disabled={!message.trim()} className="flex items-center gap-2 rounded-lg bg-emerald-800 px-4 py-2.5 text-sm font-bold text-white disabled:opacity-40"><Send className="size-4" />Send message</button></div></div></div>}
  </main>
}
